
include:
  - ./dify/docker-compose.yaml  # http://localhost:7080
  - ./bifrost/compose.yaml      # http://ai-proxy/v1
  # - ./litellm/compose.yaml      # http://ai-proxy/v1
  # - ./nginx/compose.yaml        # http://ai-proxy/v1
