apiVersion: v1
kind: ConfigMap
metadata:
  name: bifrost-mirror
  namespace: dify
data:
  pricing.json: "{}"
  model_parameters.json: "{}"
---
apiVersion: v1
kind: Service
metadata:
  name: bifrost-mirror
  namespace: dify
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: bifrost-mirror
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bifrost-mirror
  namespace: dify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bifrost-mirror
  template:
    metadata:
      labels:
        app: bifrost-mirror
    spec:
      containers:
      - name: bifrost-mirror
        image: nginx:1.25.3
        ports:
          - containerPort: 80
        volumeMounts:
          - name: html
            mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          configMap:
            name: bifrost-mirror
        