apiVersion: v1
kind: Service
metadata:
  name: zarf-connect-harbor
  namespace: harbor
  labels:
    zarf.dev/package: harbor
    zarf.dev/connect-name: harbor
  annotations:
    zarf.dev/connect-description: Harbor Console 
spec:
  type: ClusterIP
  ports:
    - name: http-internal
      port: 443
      protocol: TCP
  selector:
    app: rancher
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
