apiVersion: v1
kind: ConfigMap
metadata:
  name: slim-kafka-print-job-env
  namespace: flink-job
data:
  SMALLRYE_CONFIG_PROFILE: k8s
  # SMALLRYE_CONFIG_LOCATIONS: file:/opt/flink/config/
  ENABLE_BUILT_IN_PLUGINS: flink-s3-fs-presto-1.20.4.jar
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: slim-kafka-print-job-config
  namespace: flink-job
data:
  application.yaml: |
    vars:
      kafka:
        topic: test-topic
        options:
          properties.group.id: flink-simple-kafka-print-job
          properties.bootstrap.servers: my-cluster-kafka-bootstrap.kafka-operator:9092
          scan.startup.mode: earliest-offset  # latest-offset
          format: raw

          # properties.security.protocol: SSL
          # properties.ssl.truststore.type: PEM
          # properties.ssl.endpoint.identification.algorithm: " "
          # properties.ssl.certificate.verification: 0
          # properties.ssl.truststore.certificate: classpath:certs/kafka.pem  # Replaced at Runtime
    job:
      pipelines:
        - classpath:sql/data.sql
        - file:/opt/flink/config/data.sql
  data.sql: |
    INSERT INTO sink SELECT CONCAT(log_line, ' $$$$') FROM source
