apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - flink-deploy.yaml
  - flink-config.yaml

patches:
  - path: flink-deploy-s3.yaml

secretGenerator:
  - name: simple-kafka-print-job-sec
    namespace: flink-job
    envs:
      - secret.env
    options:
      disableNameSuffixHash: true
