#type: chart
---
# Source: /var/folders/dg/zsns4b4x6jbcz945l3254t7w0000gp/T/zarf-1758529729/chart.yaml
# Source: trino/templates/configmap-catalog.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-catalog
  namespace: trino
  labels:
    helm.sh/chart: trino-1.42.1
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: trino
    app.kubernetes.io/version: "479"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: catalogs
data:
  tpcds.properties: |
    connector.name=tpcds
    tpcds.splits-per-node=4
    
  tpch.properties: |
    connector.name=tpch
    tpch.splits-per-node=4
---
# Source: /var/folders/dg/zsns4b4x6jbcz945l3254t7w0000gp/T/zarf-1758529729/chart.yaml
# Source: trino/templates/configmap-coordinator.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-coordinator
  namespace: trino
  labels:
    helm.sh/chart: trino-1.42.1
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: trino
    app.kubernetes.io/version: "479"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: coordinator
data:
  node.properties: |
    node.environment=production
    node.data-dir=/data/trino
    plugin.dir=/usr/lib/trino/plugin

  jvm.config: |
    -server
    -agentpath:/usr/lib/trino/bin/libjvmkill.so
    -Xmx2G
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+ExitOnOutOfMemoryError
    -XX:-OmitStackTraceInFastThrow
    -XX:ReservedCodeCacheSize=512M
    -XX:PerMethodRecompilationCutoff=10000
    -XX:PerBytecodeRecompilationCutoff=10000
    -Djdk.attach.allowAttachSelf=true
    -Djdk.nio.maxCachedBufferSize=2000000
    # Allow loading dynamic agent used by JOL
    -XX:+EnableDynamicAgentLoading
  
    # https://bugs.openjdk.org/browse/JDK-8329528
    -XX:+UnlockDiagnosticVMOptions
    -XX:G1NumCollectionsKeepPinned=10000000

  config.properties: |
    coordinator=true
    node-scheduler.include-coordinator=false
    http-server.http.port=8080
    query.max-memory=4GB
    query.max-memory-per-node=1GB
    discovery.uri=http://localhost:8080
    http-server.process-forwarded=true

  log.properties: |
    io.trino=INFO
---
# Source: /var/folders/dg/zsns4b4x6jbcz945l3254t7w0000gp/T/zarf-1758529729/chart.yaml
# Source: trino/templates/configmap-coordinator.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-schemas-volume-coordinator
  namespace: trino
  labels:
    helm.sh/chart: trino-1.42.1
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: trino
    app.kubernetes.io/version: "479"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: coordinator
data:
---
# Source: /var/folders/dg/zsns4b4x6jbcz945l3254t7w0000gp/T/zarf-1758529729/chart.yaml
# Source: trino/templates/configmap-worker.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-worker
  namespace: trino
  labels:
    helm.sh/chart: trino-1.42.1
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: trino
    app.kubernetes.io/version: "479"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: worker
data:
  node.properties: |
    node.environment=production
    node.data-dir=/data/trino
    plugin.dir=/usr/lib/trino/plugin

  jvm.config: |
    -server
    -agentpath:/usr/lib/trino/bin/libjvmkill.so
    -Xmx2G
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+ExitOnOutOfMemoryError
    -XX:-OmitStackTraceInFastThrow
    -XX:ReservedCodeCacheSize=512M
    -XX:PerMethodRecompilationCutoff=10000
    -XX:PerBytecodeRecompilationCutoff=10000
    -Djdk.attach.allowAttachSelf=true
    -Djdk.nio.maxCachedBufferSize=2000000
    # Allow loading dynamic agent used by JOL
    -XX:+EnableDynamicAgentLoading
  
    # https://bugs.openjdk.org/browse/JDK-8329528
    -XX:+UnlockDiagnosticVMOptions
    -XX:G1NumCollectionsKeepPinned=10000000

  config.properties: |
    coordinator=false
    http-server.http.port=8080
    query.max-memory=4GB
    query.max-memory-per-node=1GB
    discovery.uri=http://trino:8080
    http-server.process-forwarded=true

  log.properties: |
    io.trino=INFO
---
# Source: /var/folders/dg/zsns4b4x6jbcz945l3254t7w0000gp/T/zarf-1758529729/chart.yaml
# Source: trino/templates/configmap-worker.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-schemas-volume-worker
  namespace: trino
  labels:
    helm.sh/chart: trino-1.42.1
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: trino
    app.kubernetes.io/version: "479"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: worker
data:
---
# Source: /var/folders/dg/zsns4b4x6jbcz945l3254t7w0000gp/T/zarf-1758529729/chart.yaml
# Source: trino/templates/service-coordinator.yaml
apiVersion: v1
kind: Service
metadata:
  name: trino
  namespace: trino
  labels:
    helm.sh/chart: trino-1.42.1
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: trino
    app.kubernetes.io/version: "479"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: coordinator
  annotations:
    {}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: trino
    app.kubernetes.io/component: coordinator
---
# Source: /var/folders/dg/zsns4b4x6jbcz945l3254t7w0000gp/T/zarf-1758529729/chart.yaml
# Source: trino/templates/service-worker.yaml
apiVersion: v1
kind: Service
metadata:
  name: trino-worker
  namespace: trino
  labels:
    helm.sh/chart: trino-1.42.1
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: trino
    app.kubernetes.io/version: "479"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: worker
  annotations:
    {}
spec:
  clusterIP: None
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: trino
    app.kubernetes.io/component: worker
---
# Source: /var/folders/dg/zsns4b4x6jbcz945l3254t7w0000gp/T/zarf-1758529729/chart.yaml
# Source: trino/templates/deployment-coordinator.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-coordinator
  namespace: trino
  labels:
    helm.sh/chart: trino-1.42.1
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: trino
    app.kubernetes.io/version: "479"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: coordinator
    trino.io/network-policy-protection: disabled
  annotations:
    {}
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: trino
      app.kubernetes.io/instance: trino
      app.kubernetes.io/component: coordinator
  template:
    metadata:
      annotations:
        checksum/catalog-config: 20ad7790f2f049c8ad05e6a983e1f35416c52cc89d1adcbeb81f454d5bbedc04
        checksum/coordinator-config: d65f2428c5765af7c8b14d349c7945450ea72c9b3e5bfd0d189a313ae6febd68

      labels:
        helm.sh/chart: trino-1.42.1
        app.kubernetes.io/name: trino
        app.kubernetes.io/instance: trino
        app.kubernetes.io/version: "479"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: coordinator
        trino.io/network-policy-protection: disabled
    spec:
      serviceAccountName: default
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
      volumes:
        - name: config-volume
          configMap:
            name: trino-coordinator
        - name: catalog-volume
          configMap:
            name: trino-catalog
        - name: schemas-volume
          configMap:
            name: trino-schemas-volume-coordinator
        - emptyDir: {}
          name: catalog-volume
      terminationGracePeriodSeconds: 30
      containers:
        - name: trino-coordinator
          image: trinodb/trino:480
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          env:
            []
          envFrom:
            []
          volumeMounts:
            - mountPath: /etc/trino
              name: config-volume
            - mountPath: /etc/trino/catalog
              name: catalog-volume
            - mountPath: /etc/trino/schemas
              name: schemas-volume
            - mountPath: /etc/trino/catalog-extra
              name: catalog-volume-extra
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/info
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            exec:
              command: [/usr/lib/trino/bin/health-check]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          lifecycle:
            {}
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 0.5
              memory: 2Gi
        - env:
          - name: LABEL
            value: trino-catalog
          - name: LABEL_VALUE
            value: "true"
          - name: RESOURCE
            value: both
          - name: FOLDER
            value: /etc/trino/catalog-extra
          - name: UNIQUE_FILENAMES
            value: "true"
          image: kiwigrid/k8s-sidecar:1.25.2
          name: catalog-sidecar
          volumeMounts:
          - mountPath: /etc/trino/catalog
            name: catalog-volume-dynamic
---
# Source: /var/folders/dg/zsns4b4x6jbcz945l3254t7w0000gp/T/zarf-1758529729/chart.yaml
# Source: trino/templates/deployment-worker.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-worker
  namespace: trino
  labels:
    helm.sh/chart: trino-1.42.1
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: trino
    app.kubernetes.io/version: "479"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: worker
    trino.io/network-policy-protection: disabled
  annotations:
    {}
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: trino
      app.kubernetes.io/instance: trino
      app.kubernetes.io/component: worker
  template:
    metadata:
      annotations:
        checksum/catalog-config: 20ad7790f2f049c8ad05e6a983e1f35416c52cc89d1adcbeb81f454d5bbedc04
        checksum/worker-config: f5853ccaeeff7d427fc29842108c41de08a555870a75af62a83729693d8f24e9
      labels:
        helm.sh/chart: trino-1.42.1
        app.kubernetes.io/name: trino
        app.kubernetes.io/instance: trino
        app.kubernetes.io/version: "479"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: worker
        trino.io/network-policy-protection: disabled
    spec:
      serviceAccountName: default
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
      volumes:
        - name: config-volume
          configMap:
            name: trino-worker
        - name: catalog-volume
          configMap:
            name: trino-catalog
        - name: schemas-volume
          configMap:
            name: trino-schemas-volume-worker
      terminationGracePeriodSeconds: 30
      containers:
        - name: trino-worker
          image: trinodb/trino:480
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          env:
            []
          envFrom:
            []
          volumeMounts:
            - mountPath: /etc/trino
              name: config-volume
            - mountPath: /etc/trino/catalog
              name: catalog-volume
            - mountPath: /etc/trino/schemas
              name: schemas-volume
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/info
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            exec:
              command: [/usr/lib/trino/bin/health-check]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          lifecycle:
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 0.5
              memory: 2Gi
---
# Source: /var/folders/dg/zsns4b4x6jbcz945l3254t7w0000gp/T/zarf-1758529729/chart.yaml
# Source: trino/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trino-coordinator
  namespace: trino
  labels:
    helm.sh/chart: trino-1.42.1
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: trino
    app.kubernetes.io/version: "479"
    app.kubernetes.io/managed-by: Helm
  annotations:
    {}
spec:
  ingressClassName: 
  rules:
    - host: "trino.local"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: trino
                port:
                  number: 8080

---
apiVersion: v1
kind: Pod
metadata:
  name: trino-test-connection
  labels:
    helm.sh/chart: trino-1.42.1
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: trino
    app.kubernetes.io/version: "479"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: test
    test: connection
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: cli
      image: trinodb/trino:480
      command: ['trino']
      args:
      - trino://trino:8080
      - --user=admin
      - --debug
      - --execute=SELECT COUNT(*) FROM tpch.tiny.nation
      - --no-progress
  restartPolicy: Never
---
#type: manifest
#source: /var/folders/dg/zsns4b4x6jbcz945l3254t7w0000gp/T/zarf-791413692/trino-sidecar-rolebinding/manifests/trino-sidecar-rolebinding-0.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: trino-sidecar-role
  namespace: trino
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trino-sidecar-rolebinding
  namespace: trino
  labels:
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: trino
    app.kubernetes.io/component: sidecar
    # app.kubernetes.io/part-of: trino
    # app.kubernetes.io/managed-by: zarf
subjects:
  - kind: ServiceAccount
    name: default
    namespace: trino
roleRef:
  kind: Role
  name: trino-sidecar-role
  apiGroup: rbac.authorization.k8s.io
---
#type: manifest
#source: /var/folders/dg/zsns4b4x6jbcz945l3254t7w0000gp/T/zarf-791413692/trino-catalog-iceberg/manifests/trino-catalog-iceberg-0.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-catalog-iceberg
  namespace: trino
  labels:
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: trino
    app.kubernetes.io/component: catalog
    # app.kubernetes.io/part-of: trino
    # app.kubernetes.io/managed-by: zarf
    trino-catalog: "true"
data:
  iceberg.properties: |-
    # https://trino.io/docs/current/connector/iceberg.html#general-configuration
    connector.name=iceberg
    iceberg.catalog.type=rest
    iceberg.rest-catalog.uri=http://iceberg-rest.iceberg-system:8181
    iceberg.rest-catalog.warehouse=s3://minio.iceberg-system:9000/datalake/warehouse

    # Native S3 성능 가속화
    fs.native-s3.enabled=true
    s3.endpoint=http://minio.iceberg-system:9000
    s3.aws-access-key=minioadmin
    s3.aws-secret-key=minioadmin
    s3.path-style-access=true

    # Iceberg 480 기능 활성화
    iceberg.register-table-procedure.enabled=true
---
