apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: test-topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 6
  replicas: 3
  config:
    min.insync.replicas: 2
    unclean.leader.election.enable: false
  #   retention.ms: 86400000
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: dual-role
  namespace: kafka-operator
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 3
  roles:
    - controller
    - broker
  storage:
    # type: ephemeral
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 1Gi
        # kafkaMetadata: shared
        class: "###ZARF_VAR_STORAGE_CLASS###"
        deleteClaim: false
---
apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka-operator
spec:
  kafka:
    version: 4.1.1
    metadataVersion: 4.2-IV1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      # https://strimzi.io/blog/2019/05/23/accessing-kafka-part-5/
      - name: external
        port: 9094
        tls: true
        # type: nodeport
        type: ingress
        configuration:
          bootstrap:
            host: bootstrap.my-cluster.kafka.local
          brokers:
            - broker: 0
              host: broker-0.my-cluster.kafka.local
            - broker: 1
              host: broker-1.my-cluster.kafka.local
            - broker: 2
              host: broker-2.my-cluster.kafka.local

    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
    
    # logging:
    #   type: inline
    #   loggers:
    #     kafka.root.logger.level: INFO
    #     kafka.network.Processor: TRACE
    #     kafka.network.RequestChannel$: TRACE
    #     kafka.server.KafkaApis: TRACE

  # https://strimzi.io/blog/2020/06/15/cruise-control/
  cruiseControl: {}

  entityOperator:
    topicOperator: {}
    userOperator: {}
---

