---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-fleet-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-fleet-local-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-turtles-system
