apiVersion: zarf.dev/v1alpha1
kind: ZarfPackageConfig
metadata:
  name: rke2-setup
  description: ""
  version: v0.0.1

variables:
  - name: DEFAULT_PATH_FOR_NON_LISTED_NODES
    description: Default path for non-listed nodes in the local-path-provisioner configuration
    default: /data
    prompt: true

components:
  - name: rancher-local-path-provisioner-images
    required: true
    actions:
      onCreate:
        before:
          - cmd: scripts/local-path-provisioner/images_before.sh
        after:
          - cmd: scripts/local-path-provisioner/images_after.sh
    files:
      - source: local-path-provisioner-v0.0.35.tar
        target: /var/lib/rancher/rke2/agent/images/local-path-provisioner-v0.0.35.tar
      - source: busybox-1.36.tar
        target: /var/lib/rancher/rke2/agent/images/busybox-1.36.tar
  
  - name: rancher-local-path-provisioner-helm-rke2
    actions:
      onCreate:
        before:
          - cmd: scripts/local-path-provisioner/helm_before.sh
        after:
          - cmd: "rm -rf .tmp"
    files:
      - source: .tmp/rke2-helm-local-path-provisioner.yaml
        target: /var/lib/rancher/rke2/server/manifests/rke2-helm-local-path-provisioner.yaml
    
  - name: rancher-local-path-provisioner-helm
    charts:
      - name: local-path-provisioner
        version: v0.0.35
        namespace: local-path-storage
        url: https://github.com/rancher/local-path-provisioner.git
        gitPath: deploy/chart/local-path-provisioner
        valuesFiles:
          - values-local-path-provisioner.yaml
