apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: counter-job
  namespace: default
spec:
  image: counter-job
  flinkVersion: v1_20
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: 1
    parallelism.default: 1
  serviceAccount: flink
  jobManager:
    replicas: 1
    resource:
      cpu: 1
      memory: 1024m
  taskManager:
    replicas: 1
    resource:
      cpu: 1
      memory: 1024m
  job:
    jarURI: local:///opt/flink/lib/counter-jobs.jar
    entryClass: com.airgap.flink.CounterJob
    state: running
    savepointNonce: 0