mode: deployment

# https://opentelemetry.io/docs/collector/distributions/
image:
  # repository: otel/opentelemetry-collector
  repository: otel/opentelemetry-collector-contrib
  # repository: otel/opentelemetry-collector-k8s
  # repository: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s

command:
  name: otelcol-contrib

extraEnvsFrom:
  - secretRef:
      name: otel-collector-sec

config:
  receivers:
    kafka/topic_a:
      brokers: 
        - my-cluster-kafka-bootstrap.kafka-operator.svc.cluster.local:9092
      topics: [ app-log-topic-a ]
      encoding: text

  processors:
    batch:
      send_batch_size: 8192
      timeout: 1s
    transform/hostname:
      error_mode: ignore
      log_statements:
        - context: resource
          statements:
            - set(attributes["host.hostname"], hostname())  # or hardcode
            - set(attributes["host.ip"], ip())  # or hardcode
        - context: log
          statements:
            - merge_maps(attributes, ParseJSON(body), "upsert")
            # Parse timestamp from fluent-bit
            - set(time_unix_nano, Int(attributes["@timestamp"] * 1000000000)) where attributes["@timestamp"] != nil
            - delete_key(attributes, "@timestamp")
    # resource/attributes:
    #   actions:
    #     - key: host.hostname
    #       value: ${HOSTNAME}
    #       action: upsert
    #     - key: host.ip
    #       value: ${HOST_IP}
    #       action: upsert

  exporters:
    debug:
      verbosity: debug

    opensearch/target_a:
      # Important: otelhttp exporter automatically appends "/v1/logs" to the endpoint.
      # eg. "https://my-storage:4318" becomes "https://my-storage:4318/v1/logs"
      http:
        endpoint: https://opensearch.local:4318
        headers:
          # X-API-Key: ${env:OPENSEARCH_KEY_TARGET_A}          # from secret
          Authorization: ApiKey ${env:OPENSEARCH_KEY_TARGET_A} # from secret
        tls:  # true if you want to enable TLS, false otherwise
          insecure_skip_verify: true
      logs_index: logs

  service:
    # telemetry:
    #   logs:
    #     level: debug
    #     encoding: json

    pipelines:
      metrics: null
      traces: null
      logs/pipeline_a:
        receivers: [ kafka/topic_a ]
        processors: [ transform/hostname, batch ]
        exporters: [ debug, opensearch/target_a ]
