global:
  marketplace:
    enabled: true

  # extraEnvs:
  #   - name: FORCE_VERIFYING_SIGNATURE
  #     value: "false"

image:
  api:
    repository: langgenius/dify-api
    tag: 1.14.2
    # pullPolicy: IfNotPresent
  pluginDaemon:
    repository: langgenius/dify-plugin-daemon
    tag: 0.6.1-local
  web:
    repository: langgenius/dify-web
    tag: 1.14.2
  sendbox:
    repository: langgenius/dify-sandbox
    tag: 0.2.15
  proxy:
    repository: nginx
    tag: 1.25.3
  # ssrfProxy:
  #   repository: ubuntu/squid
  #   tag: 

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
  # className: "nginx"
  hosts:
  - host: dify.local
    paths:
      - path: /
        pathType: ImplementationSpecific

api:
  extraEnv:
    # TODO: ...
    - name: FORCE_VERIFYING_SIGNATURE
      value: "false"

pluginDaemon:
  envs:
    # - name: SERVER_PORT
    #   value: "5002"
    # - name: MAX_PLUGIN_PACKAGE_SIZE
    #   value: "52428800"
    # - name: PPROF_ENABLED
    #   value: "false"
    - name: FORCE_VERIFYING_SIGNATURE
      value: "false"
    # - name: DB_DATABASE
    #   value: "dify_plugin"
    # - name: PLUGIN_REMOTE_INSTALLING_HOST
    #   value: "0.0.0.0"
    # - name: PLUGIN_REMOTE_INSTALLING_PORT
    #   value: "5003"

worker:
  extraEnv:
    - name: FORCE_VERIFYING_SIGNATURE
      value: "false"

redis:
  architecture: standalone
  global:
    storageClass: standard
  image:
    repository: bitnamilegacy/redis
    tag: 8.2.1

postgresql:
  enabled: true
  name: postgres
  architecture: standalone
  global:
    storageClass: standard
  image:
    repository: bitnamilegacy/postgresql
    tag: 17.6.0

weaviate:
  # TODD:
  enabled: false

externalS3:
  enabled: true
  endpoint: "###ZARF_VAR_S3_ENDPOINT###"
  pathStyle: true
  accessKey: "###ZARF_VAR_S3_ACCESS_KEY###"
  secretkey: "###ZARF_VAR_S3_SECRET_KEY###"
  # bucketName:
  #   api: difyai
  #   pluginDaemon: 
  useIAM: false
  region: us-east-1

minio:
  embedded: false
  persistence:
    enabled: true
    storageClass: standard
