global:
  marketplace:
    enabled: true

  # extraEnvs:
  #   - name: FORCE_VERIFYING_SIGNATURE
  #     value: "false"

# image:
#   api:
#     repository: langenius:dify-api
#     tag: 1.14.2
#     # pullPolicy: IfNotPresent
#   pluginDaemon:
#     repository: langenius:dify-plugin-daemon
#     tag: 0.6.1-local
#   web:
#     repository: langenius:dify-web
#     tag: 1.14.2
#   sendbox:
#     repository: langenius:dify-sandbox
#     tag: 0.2.15
#   proxy:
#     repository: nginx
#     tag: 1.25.3
#   ssrfProxy:
#     repository: ubuntu/squid
#     tag: 

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
  # className: "nginx"
  hosts:
  - host: dify.local
    paths:
      - path: /
        patyType: ImplementationSpecific

api:
  extraEnv:
    # TODO: ...
    - name: FORCE_VERIFYING_SIGNATURE
      value: "false"

pluginDaemon:
  envs:
    # - name: SERVER_PORT
    #   value: "5002"
    # - name: MAX_PLUGIN_PACKAGE_SIZE
    #   value: "52428800"
    # - name: PPROF_ENABLED
    #   value: "false"
    - name: FORCE_VERIFYING_SIGNATURE
      value: "false"
    # - name: DB_DATABASE
    #   value: "dify_plugin"
    # - name: PLUGIN_REMOTE_INSTALLING_HOST
    #   value: "0.0.0.0"
    # - name: PLUGIN_REMOTE_INSTALLING_PORT
    #   value: "5003"

worker:
  extraEnv:
    - name: FORCE_VERIFYING_SIGNATURE
      value: "false"

redis:
  architecture: standalone
  global:
    storageClass: standard
  image:
    repository: bitnamilegary/redis
    tag: 7.2.4

postgresql:
  enabled: true
  name: postgres
  architecture: standalone
  global:
    storageClass: standard
  image:
    repository: bitnamilegary/postgresql
    tag: 16.3.0

weaviate:
  # TODD:
  enabled: false

externalS3:
  enabled: true
  endpoint: http://your-s3:port
  pathStyle: true
  accessKey:
  secretkey:
  bucketName:
    api: your-bucket
    pluginDaemon: your-bucket
  useIAM: false
  region: us-east-1

# minio:
#   embedded: false
#   persistence:
#     enabled: true
#     storageClass: standard
