# https://ui.docs.kafbat.io/configuration/helm-charts/quick-start
# https://artifacthub.io/packages/helm/kafka-ui/kafka-ui
yamlApplicationConfig:
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false
  kafka:
    clusters:
      - name: my-cluster
        bootstrapServers: my-cluster-kafka-bootstrap.kafka-operator:9092

service:
  type: NodePort

ingress:
  enabled: true
  host: kafka-ui.local
  # ingressClassName: nginx
  # tls:
  #   enabled: false
  #   secretName: kafka-ui-tls
