smallrye:
  config:
    profile: local
    mapping:
      validate-unknown: false

job:
  name: slim-kafka-print-job
  schemas:
    - classpath:sql/schema.sql
  pipelines:
    - classpath:sql/data.sql
