# https://nightlies.apache.org/flink/flink-kubernetes-operator-docs-release-1.15/docs/try-flink-kubernetes-operator/quick-start/#submitting-a-flink-job
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: quickstart   # Changed
spec:
  image: flink:2.2
  flinkVersion: v2_2
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: 1  # Changed
  serviceAccount: flink
  jobManager:
    resource:
      memory: 1024m  # Changed
      cpu: 1
  taskManager:
    resource:
      memory: 1024m  # Changed
      cpu: 1
  job:
    jarURI: local:///opt/flink/examples/streaming/StateMachineExample.jar
    parallelism: 1   # Changed
    upgradeMode: stateless
  ingress:  # Added
    template: flink.local/{{namespace}}/{{name}}/(/|$)(.*)
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2

# apiVersion: flink.apache.org/v1beta1
# kind: FlinkDeployment
# metadata:
#   name: flink-quickstart
#   namespace: default
# spec:
#   image: flink:1.20
#   flinkVersion: v1_20
#   flinkConfiguration:
#     taskmanager.numberOfTaskSlots: "2"
#     parallelism.default: "2"
#   serviceAccount: flink-service-account
#   jobManager:
#     resource:
#       memory: "1024m"
#       cpu: 1
#   taskManager:
#     resource:
#       memory: "1024m"
#       cpu: 1
#   job:
#     jarURI: local:///opt/flink/examples/streaming/StateMachineExample.jar
#     entryClass: org.apache.flink.streaming.examples.statemachine.StateMachineExample
#     args:
#       - "--input"
#       - "/opt/flink/examples/streaming/statemachine/event-data"
#     parallelism: 2
#     upgradeMode: savepoint
#     state: running
#     savepointTriggerNonce: 0