services:
  jobmanager:
    image: ${FLINK_IMAGE:?FLINK_IMAGE requied(.env)}
    # command: standalone-job --job-classname com.airgap.flink.CounterJob
    # command: java --version
    command: standalone-job --job-classname ${MAIN_CLASS:?MAIN_CLASS required(.env)}
    ports:
      - 8081:8081  # Flink Web UI Port
    extra_hosts:
      - redpanda:host-gateway
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        parallelism.default: 1
  
  taskmanager:
    image: ${FLINK_IMAGE:?FLINK_IMAGE requied(.env)}
    command: taskmanager
    extra_hosts:
      - redpanda:host-gateway
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        parallelism.default: 1
        jobmanager.numberOfTaskSlots: 1
