apiVersion: zarf.dev/v1alpha1
kind: ZarfPackageConfig
metadata:
  name: rke2-harbor
  description: ""
  version: v0.0.1

components:
  - name: rke2-images-harbor
    required: true
    actions:
      onCreate:
        before:
          - cmd: scripts/harbor/images.sh download
        after:
          - cmd: scripts/harbor/images.sh clean
    files:
      - source: goharbor-chartmuseum-photon-v1.10.2.tar
        target: /var/lib/rancher/rke2/agent/images/goharbor-chartmuseum-photon-v1.10.2.tar
      - source: goharbor-clair-adapter-photon-v1.10.2.tar
        target: /var/lib/rancher/rke2/agent/images/goharbor-clair-adapter-photon-v1.10.2.tar
      - source: goharbor-clair-photon-v1.10.2.tar
        target: /var/lib/rancher/rke2/agent/images/goharbor-clair-photon-v1.10.2.tar
      - source: goharbor-harbor-core-v1.10.2.tar
        target: /var/lib/rancher/rke2/agent/images/goharbor-harbor-core-v1.10.2.tar
      - source: goharbor-harbor-db-v1.10.2.tar
        target: /var/lib/rancher/rke2/agent/images/goharbor-harbor-db-v1.10.2.tar
      - source: goharbor-harbor-jobservice-v1.10.2.tar
        target: /var/lib/rancher/rke2/agent/images/goharbor-harbor-jobservice-v1.10.2.tar
      - source: goharbor-harbor-portal-v1.10.2.tar
        target: /var/lib/rancher/rke2/agent/images/goharbor-harbor-portal-v1.10.2.tar
      - source: goharbor-harbor-registryctl-v1.10.2.tar
        target: /var/lib/rancher/rke2/agent/images/goharbor-harbor-registryctl-v1.10.2.tar
      - source: goharbor-notary-server-photon-v1.10.2.tar
        target: /var/lib/rancher/rke2/agent/images/goharbor-notary-server-photon-v1.10.2.tar
      - source: goharbor-notary-signer-photon-v1.10.2.tar
        target: /var/lib/rancher/rke2/agent/images/goharbor-notary-signer-photon-v1.10.2.tar
      - source: goharbor-redis-photon-v1.10.2.tar
        target: /var/lib/rancher/rke2/agent/images/goharbor-redis-photon-v1.10.2.tar
      - source: goharbor-registry-photon-v1.10.2.tar
        target: /var/lib/rancher/rke2/agent/images/goharbor-registry-photon-v1.10.2.tar
  
  - name: rke2-helm-harbor
    actions:
      onCreate:
        before:
          - cmd: scripts/harbor/helm_before.sh
        after:
          - cmd: rm -rf .tmp
    files:
      - source: .tmp/rke2-helm-harbor.yaml
        target: /var/lib/rancher/rke2/server/manifests/rke2-helm-harbor.yaml
  
  - name: harbor-helm
    charts:
      - name: harbor
        version: 1.3.2
        namespace: harbor
        url: https://helm.goharbor.io
        valuesFiles:
          - values-harbor.yaml
    # for `zarf dev find-images`
    # images:
    #   - busybox:latest
    #   - goharbor/chartmuseum-photon:v1.10.2
    #   - goharbor/clair-adapter-photon:v1.10.2
    #   - goharbor/clair-photon:v1.10.2
    #   - goharbor/harbor-core:v1.10.2
    #   - goharbor/harbor-db:v1.10.2
    #   - goharbor/harbor-jobservice:v1.10.2
    #   - goharbor/harbor-portal:v1.10.2
    #   - goharbor/harbor-registryctl:v1.10.2
    #   - goharbor/notary-server-photon:v1.10.2
    #   - goharbor/notary-signer-photon:v1.10.2
    #   - goharbor/redis-photon:v1.10.2
    #   - goharbor/registry-photon:v1.10.2
