apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: trino-sidecar-role
  namespace: trino
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trino-sidecar-rolebinding
  namespace: trino
  labels:
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: trino
    app.kubernetes.io/component: sidecar
    # app.kubernetes.io/part-of: trino
    # app.kubernetes.io/managed-by: zarf
subjects:
  - kind: ServiceAccount
    name: default
    namespace: trino
roleRef:
  kind: Role
  name: trino-sidecar-role
  apiGroup: rbac.authorization.k8s.io
