services:
  bifrost:
    image: maximhq/bifrost:v1.5.3
    ports:
      - 4000:8080
    environment:
      - CUSTOM_PROVIDER_URL=${CUSTOM_PROVIDER_URL}
      - CUSTOM_PROVIDER_API_KEY=${CUSTOM_PROVIDER_API_KEY}
      - CUSTOM_PROVIDER_HEADERS_API_KEY=${CUSTOM_PROVIDER_HEADERS_API_KEY}
    #   - BIFROST_PORT=7081
    #   - BIFROST_LOG_LEVEL=info
    #   - BIFROST_MODEL_DIR=/models
    volumes:
      - ./bifrost_config.json:/app/data/config.json:ro

  bifrost-mirror:
    image: nginx:alpine
    volumes:
      - ./datasheet:/usr/share/nginx/html:ro
  
  tei-embedding:
    # depends_on:
    #   - tei-embedding-init
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-latest
    ports:
      - 8000:80
    volumes:
      - ./models:/data
    command: --model-id /data --dtype float32
    # command: --model-id BAAI/bge-m3 --dtype float32
    shm_size: 2gb
    deploy:
      resources:
        limits:
          memory: 4G  # 모델 로드 피크치를 감당하도록 최소 6GB 할당
    # restart: always
  
  # hf download baai/bge-m3 --local-dir models
  # tei-embedding-init:
  #   image: ghcr.io/huggingface/text-embeddings-inference:cpu-latest
  #   command: --model-id BAAI/bge-m3 --dtype float32
  #   shm_size: 1gb
  #   volumes:
  #     - ./models:/models
