apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: counter-job

build:
  local:
    push: false
  tagPolicy:
    gitCommit:  # git describe --tags --always
  artifacts:
    - image: counter-job
      custom:
        buildCommand: ../docker/build.sh

manifests:
  rawYaml:
    - manifests/*.yaml

resourceSelector:
  allow:
    - groupKind: FlinkDeployment.flink.apache.org
      image: [".*"]
