version: '3.8'
services:
  api:
    environment:
      FORCE_VERIFYING_SIGNATURE: 'false'
      ENFORCE_LANGGENIUS_PLUGIN_SIGNATURES: 'false'
      PLUGIN_MAX_PACKAGE_SIZE: '524288000'
  worker:
    environment:
      FORCE_VERIFYING_SIGNATURE: 'false'
      ENFORCE_LANGGENIUS_PLUGIN_SIGNATURES: 'false'
      PLUGIN_MAX_PACKAGE_SIZE: '524288000'
  nginx:
    environment:
      NGINX_CLIENT_MAX_BODY_SIZE: '500M'